myhomework24/myhomework24/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')),
    # class 기반 RootView 구현
    path('', RedirectView.as_view(url='/shop/'), name='root')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
     path('__debug__/', include('debug_toolbar.urls')),
    ]

myhomework24/shop/urls.py
from django.urls import path
from shop import views

app_name = 'shop'

urlpatterns = [
    path('', views.shop_list, name="shop_list"),
    path('<int:pk>/', views.shop_detail, name="shop_detail"),
    path('new/', views.shop_new, name="shop_new"),
    path('<int:pk>/edit/', views.shop_edit, name="shop_edit"),
    path('<int:pk>/delete/', views.shop_delete, name="shop_delete"),
    path('<int:pk>/review/new', views.review_new, name="review_new"),
    path('<int:post_pk>/review/<int:pk>/edit/', views.review_edit, name="review_edit"),
    path('<int:post_pk>/review/<int:pk>/delete/', views.review_delete, name="review_delete"),
]

myhomework24/shop/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse


class TimestampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Category(TimestampedModel):
    name = models.CharField(max_length=20, unique=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ['name']


class Shop(TimestampedModel):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=20, db_index=True)
    photo = models.ImageField(upload_to="shop/shop/%Y/%m/%d")
    description = models.TextField()
    telephone = models.CharField(
        max_length=15,
        validators=[
            RegexValidator(r"^\d{3,4}-?\d{3,4}-?\d{4}$")
        ],
        help_text="입력 예시) 042-1234-5678"
    )
    tag_set = models.ManyToManyField('Tag', blank=True)

    def get_absolute_url(self):
        return reverse("shop:shop_detail", args=[self.post.pk])

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ["-id"]


class Review(TimestampedModel):
    post = models.ForeignKey(Shop, on_delete=models.CASCADE)
    message = models.TextField()

    def __str__(self):
        return self.message

    class Meta:
        ordering = ["-id"]


class Tag(TimestampedModel):
    name = models.CharField(max_length=20, unique=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ["name"]

myhomework24/shop/forms.py
from django import forms
from shop.models import Shop, Review, Tag


class ShopForm(forms.ModelForm):
    tags = forms.CharField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.pk:
            tag_qs = self.instance.tag_set.all()
            tags =", ".join([tag.name for tag in tag_qs])
            self.fields["tags"].initial = tags

    def _save_m2m(self):
        saved_shop = super()._save_m2m()
        tag_list = []
        tags = self.cleaned_data.get("tags", "")
        for word in tags.split(","):
            tag_name = word.strip()
            tag, __ = Tag.objects.get_or_create(name=tag_name)
            tag_list.append(tag)

        self.instance.tag_set.clear()
        self.instance.tag_set.add(*tag_list)

    class Meta:
        model = Shop
        fields = "__all__"


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = "__all__"

myhomework24/shop/views.py
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from shop.forms import ShopForm, ReviewForm
from shop.models import Shop, Review


class ShopListView(ListView):
    model = Shop

    def get_queryset(self):
        qs = super().get_queryset()
        query = self.request.GET.get("query", "").strip()
        if query:
            qs = qs.filter(name__icontains=query)
        return qs


shop_list = ShopListView.as_view(
    model=Shop
)

shop_detail = DetailView.as_view(
    model=Shop
)

shop_new = CreateView.as_view(
    model=Shop,
    form_class=ShopForm,
)

shop_edit = UpdateView.as_view(
    model=Shop,
    form_class=ShopForm,
)

shop_delete = DeleteView.as_view(
    model=Shop,
)

review_new = CreateView.as_view(
    model=Review,
    form_class=ReviewForm,
)

review_edit = UpdateView.as_view(
    model=Review,
    form_class=ReviewForm,
)

review_delete = DeleteView.as_view(
    model=Review,
    success_url=reverse_lazy("shop:shop_list")
)

myhomework24/myhomework24/templates/layout.html
{% load bootstrap5 %}

<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>#Shop#Shop#</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>

<h1>잡Shop</h1>

{% block content %}

{% endblock %}

<hr>

{% block footer %}
{% endblock %}

<hr>
&copy; 2021.12.16. Shop company.


</body>
</html>

myhomework24/shop/templates/shop/layout.html
{% extends "layout.html" %}

myhomework24/shop/templates/shop/review_confirm_delete.html
{% extends "shop/layout.html" %}
{% load bootstrap5 %}

{% block content %}
    <h2>댓글을 삭제하시겠습니까?</h2>
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <input type="submit" value="댓글삭제">
    </form>
{% endblock %}

myhomework24/shop/templates/shop/review_form.html
{% extends "shop/layout.html" %}
{% load bootstrap5 %}

{% block content %}

    <h3>Review Comment</h3>

    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}

        <input type="submit" value="수정하기">

    </form>
{% endblock %}

myhomework24/shop/templates/shop/shop_confirm_delete.html
{% extends "shop/layout.html" %}
{% load bootstrap5 %}

{% block content %}
    <h2>등록된 가게를 삭제하시겠습니까?</h2>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="submit" value="가게 삭제하기">
    </form>

    <a href="{% url "shop:shop_detail" shop.pk %}">
     돌아가기
    </a>
{% endblock %}

myhomework24/shop/templates/shop/shop_detail.html
{% extends "shop/layout.html" %}

{% block header %}
    <a href="{% url "shop:review_new" post_pk.pk %}">
        리뷰 쓰기
    </a>
{% endblock %}

{% block content %}

    <h4>
    {{ shop.name }}
    </h4>

    <img src="{{ shop.photo.url }}" alt="{{ shop.name }}">

    {{ shop.description|linebreaks }}

    <hr>
    {% for tag in object.tag_set.all %}
        <p class="badge bg-success">
        {{ tag.name }}
        </p>
    {% endfor %}
    <hr>

    <a href="{% url "shop:shop_new" %}" class="btn btn-success">
    가게 등록
    </a>
    <a href="{% url "shop:shop_edit" shop.pk %}" class="btn btn-success">
    가게 수정
    </a>
    <a href="{% url "shop:shop_list" %}">
    메인으로
    </a>


    <ul>
        {% for review in object.review_set.all %}
        <li>
            {{ review.message }}
            <a href="{% url "shop:review_edit" shop.pk review.pk %}">
                수정하기
            </a>
            <a href="{% url "shop:review_delete" shop.pk review.pk %}">
                삭제하기
            </a>
        </li>
        {% endfor %}
    </ul>



{% endblock %}

myhomework24/shop/templates/shop/shop_form.html
{% extends "shop/layout.html" %}
{% load bootstrap5 %}

{% block header %}

    <a href="{% url "shop:shop_list" %}" class="btn btn-primary">목록으로</a>

    {% if shop.pk %}
        <a href="{% url "shop:shop_detail" shop.pk %}" class="btn btn-primary">
            돌아가기
        </a>
    {% endif %}

{% endblock %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
        <input type="submit" value="제출하기">
    </form>
{% endblock %}

myhomework24/shop/templates/shop/shop_list.html
{% extends "shop/layout.html" %}

{% block content %}

{% block header %}
    <form action="" method="get">
        <label>
            <input type="text" name="query" value="{{ request.GET.query }}" placeholder="가게명을 입력해주세요.">
            <input type="submit" value="검색">
        </label>

    </form>
{% endblock %}

    <ul>
        {% for shop in shop_list %}
            <li>
                <a href="{% url "shop:shop_detail" shop.pk %}">
                    {{ shop.name }}
                </a>
            </li>
        {% endfor %}
    </ul>


{% endblock %}

{% block footer %}

    <a href="{% url "shop:shop_new" %}" class="btn btn-primary">가게 등록</a>

{% endblock %}