mydjango19/diary/urls.py
from django.urls import path

from diary import views

app_name = 'diary'

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("<int:pk>/", views.post_detail, name="post_detail"),
    path("new/", views.post_new, name="post_new"),
    path("<int:pk>/edit/", views.post_edit, name="post_edit"),
    # 태그 클릭시 해당값 나오게 하는 것 구현2 (url)
    path("tags/<str:tag_name>/", views.tag_detail, name="tag_detail"),
    path("<int:post_pk>/comments/new/", views.comment_new, name="comment_new"),
    path("<int:post_pk>/comments/<int:pk>/edit/", views.comment_edit, name="comment_edit"),
]

mydjango19/mydjango17/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include


# TODO : 편의상 여기에 root를 구현하지만,
# 차후 RedirectView CBV를 써서 이 구현을 제거할 예정
def root(request):
    return redirect("diary:post_list")


urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls')),
    path('', root, name="root")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path("__debug__", include(debug_toolbar.urls)),
    ]

mydjango19/diary/models.py
from django.core.validators import MinLengthValidator
from django.db import models


class TimestampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True  # 추상 클래스로서, DB 테이블이 생기지 않음.


class Post(TimestampedModel):
    author_name = models.CharField(max_length=20)
    title = models.CharField(
        max_length=200,
        db_index=True,
        validators=[
            MinLengthValidator(3),
            # MaxLengthValidator(),
        ],
    )
    content = models.TextField()
    photo = models.ImageField(upload_to="diary/post/%Y/%m/%d")
    tag_set = models.ManyToManyField("Tag", blank=True)
    ip = models.GenericIPAddressField()  # ip는 무조건 저장할것이기 때문에 필수 필드 = null

    def __str__(self) -> str:
        return f"[{self.pk}] {self.title}"

    class Meta:
        verbose_name = "포스팅"
        verbose_name_plural = "포스팅 목록"


class Comment(TimestampedModel):
    # 외래키 : 정수값
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author_name = models.CharField(max_length=20)
    message = models.TextField()

    def __str__(self) -> str:
        return self.message

    class Meta:
        verbose_name = "댓글"
        verbose_name_plural = "댓글 목록"


class Tag(TimestampedModel):
    name = models.CharField(max_length=200, db_index=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = "태그"
        verbose_name_plural = "태그 목록"

mydjango19/diary/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render


# class PostForm(forms.Form):
#    title = forms.CharField()
#    content = forms.CharField()
#    phone = forms.CharField(
#        validators=[
#            RegexValidator(r"^\d{3}-?\d{4}-?\d{4}$", message="휴대폰 번호를 입력해주세요."),
#        ]
#    )
from diary.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        # fields = "__all__"
        # 유저로부터 입력받을 필드 이름을 나열
        # 이 필드에 대해서만, html, 유효성 검사, db 저장을 함
        fields = [
            "author_name",
            "title",
            "content",
            "photo",
            "tag_set",
        ]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["author_name", "message"]


def post_new(request: HttpRequest) -> HttpResponse:
    form = PostForm
    return render(request, "diary/post_form.html", {
        "form": form,
    })

mydjango19/diary/views.py
from django.http import HttpRequest, HttpResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404
from diary.forms import PostForm, CommentForm
from diary.models import Post, Comment
from django.contrib import messages


def post_list(request: HttpRequest) -> HttpResponse:
    qs = Post.objects.all()

    query = request.GET.get("query", "")
    if query:
        qs = qs.filter(title__icontains=query)

    return render(request, "diary/post_list.html", {
        "post_list": qs,
    })


def post_detail(request: HttpRequest, pk: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=pk)

    # 위의 코드와 같은 코드
    # try:
    # post = Post.objects.get(pk=pk)  # DoesNotExitst 예외
    # except Post.DoesNotExist:
    #     raise Http404

    comment_list = post.comment_set.all()
    tag_list = post.tag_set.all()

    return render(request, "diary/post_detail.html", {
        "post": post,
        "comment_list": comment_list,
        "tag_list": tag_list,
    })


# 태그 클릭시 해당값 나오게 하는 것 구현1(view/로직)
def tag_detail(request: HttpRequest, tag_name: str) -> HttpResponse:
    qs = Post.objects.all()
    qs = qs.filter(tag_set__name=tag_name)   # tag_set__name = 키워드인자
    return render(request, "diary/tag_detail.html", {
        "tag_name": tag_name,
        "post_list": qs,
    })


def post_new(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():  # 유효성 검사
            print("유효성 검사에 통과했습니다. :", form.cleaned_data)
            post = form.save(commit=False)  # ModelForm 에서만 지원
            post.ip = request.META["REMOTE_ADDR"]
            form.save()  # ModelForm 에서만 지원
            messages.success(request, "성공적으로 저장했습니다.")
            return redirect("diary:post_list")
    else:
        form = PostForm()

    return render(request, "diary/post_form.html", {
        "form": form,
    })


def post_edit(request: HttpRequest, pk: int) -> HttpResponse:
    #아래 코드는 ModelForm에 한해서 동작하는 코드

    post = get_object_or_404(Post, pk=pk)

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():  # 유효성 검사
            form.save()
            messages.success(request, "성공적으로 저장했습니다.")
            print("유효성 검사에 통과했습니다. :", form.cleaned_data)
            return redirect("diary:post_list")
    else:
        form = PostForm(instance=post)

    return render(request, "diary/post_form.html", {
        "form": form,
    })


# /diary/100/comments/new
def comment_new(request: HttpRequest, post_pk: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=post_pk)

    if request.method == "POST":  # 항상 "POST" or "GET" 으로 대문자로 써야함
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            # form.cleaned_data     # 유효성 검사에 통과한 값(dict)들이 저장됨(form, ModelForm에도 있음)
            comment = form.save(commit=False)
            # comment.post_id = post_pk        # FK를 직접 채우진 않음
            comment.post = post
            comment.save()
            return redirect("diary:post_detail", post_pk)
    else:
        form = CommentForm()
    return render(request, "diary/comment_form.html", {
        "form": form,
    })


# /diary/100/comments/20/edit/
def comment_edit(request: HttpRequest, post_pk: int, pk: int) -> HttpResponse:
    comment = get_object_or_404(Comment, pk=pk)

    if request.method == "POST":
        form = CommentForm(request.POST, request.FILES, instance=comment)
        if form.is_valid():
            form.save()
            return redirect("diary:post_detail", post_pk)
    else:
        form = CommentForm(instance=comment)

    return render(request, "diary/comment_form.html", {
        "form": form,
    })

mydjango19/diary/templates/diary/comment_form.html
{% extends "diary/layout.html" %}
{% load bootstrap5 %}

{% block content %}
    <h2>Comment Form</h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}  {# method가 post일때만 넣을 수 있다. #}
        {% bootstrap_form form %}
        <input type="submit" value="저장하기" class="btn btn-primary">
    </form>
{% endblock %}

mydjango19/diary/templates/diary/layout.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <script src="//cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
    <style>
        body {
            padding: 2.5em;
        }
    </style>
    <title>김승아의 다이어리</title>
</head>
<body>
<div class="container">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="{% url "root" %}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
            <svg class="bi me-2" width="40" height="32">
                <use xlink:href="#bootstrap"></use>
            </svg>
            <span class="fs-4">김승아의 블로그</span>
        </a>

        <ul class="nav nav-pills">
            <li class="nav-item"><a href="#" class="nav-link active" aria-current="page">Home</a></li>
            <li class="nav-item"><a href="#" class="nav-link">Features</a></li>
            <li class="nav-item"><a href="#" class="nav-link">Pricing</a></li>
            <li class="nav-item"><a href="#" class="nav-link">FAQs</a></li>
            <li class="nav-item"><a href="#" class="nav-link">About</a></li>
        </ul>
    </header>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock %}

    <hr>
    &copy; 2021. SeungAh Company.

</div>


</body>
</html>

mydjango19/diary/templates/diary/post_detail.html
{% extends "diary/layout.html" %}

{% block content %}
    <h2>{{ post.title }}</h2>

    <p>
        태그 :
        {% for tag in tag_list %}
            <a href="{% url "diary:tag_detail" tag.name %}" class="badge bg-success">
                {{ tag.name }}
            </a>
        {% endfor %}
    </p>

    <img src="{{ post.photo.url }}" alt="{{ post.title }}">

    {{ post.content|linebreaks }}

    <h3>댓글</h3>

    <a href="{% url "diary:comment_new" post.pk %}">댓글 쓰기</a>

    <ul>
        {% for comment in comment_list %}
        <li>
            {{ comment.message }}
            by {{ comment.author_name }}
            <span title="{{ comment.created_at }}">
                at {{ comment.created_at|timesince }} 전
            </span>
            <a href="{% url "diary:comment_edit" post.pk comment.pk %}">Edit</a>
        </li>
        {% endfor %}
    </ul>

    <hr>

    <a href="{% url "diary:post_list" %}">
        목록으로
    </a>
    <br>
    <a href="{% url "diary:post_edit" post.pk %}">
        수정하기
    </a>
{% endblock %}

mydjango19/diary/templates/diary/post_form.html
{% extends "diary/layout.html" %}
{% load bootstrap5 %}

{% block content %}
    <h2>Post Form</h2>

    <form action="" method="post" enctype="multipart/form-data">  {# method를 생략하면 get 방식 #}
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="저장하기">
    </form>

{% endblock %}

mydjango19/diary/templates/diary/post_list.html
{% extends "diary/layout.html" %}

{% block content %}
    <form action="" method="get">
        <input type="text" name="query" value="{{ request.GET.query }}" placeholder="검색어를 입력해주세요.">
        <input type="submit" value="검색">
    </form>

    <div class="row" style="margin-top: 1em;">
        {% for post in post_list %}
            <div class="col-sm-6 offset-sm-3" style="margin-bottom: 1em;">
                <div class="card">
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</h5>
                        {{ post.content|truncatewords:20 }}
                        <a href="{% url "diary:post_detail" post.pk %}" class="btn btn-sm btn-primary">
                            바로 가기
                    </a>
                    </div>

                </div>

            </div>

        {% endfor %}
    </div>
    <hr>
    <a href="{% url "diary:post_new" %}" class="btn btn-primary">
        포스팅 쓰기
    </a>


{% endblock %}

mydjango19/diary/templates/diary/tag_detail.html
{% extends "diary/layout.html" %}

{% block content %}
    <h2>{{ tag_name }}</h2>

    <div>
        {% for post in post_list %}
            <div>
                <a href="{% url "diary:tag_detail" post.pk %}">
                    {{ post.title }}
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}