mydjango23/blog/urls.py
from django.urls import path

from blog.views import cbv as views
# from blog.views import fbv as views

app_name = "blog"

urlpatterns = [
    path('', views.post_list, name="post_list"),
    path('<int:pk>/', views.post_detail, name="post_detail"),
    path('new/', views.post_new, name="post_new"),
    path('<int:pk>/edit/', views.post_edit, name="post_edit"),
    # 삭제 주소
    path('<int:pk>/delete/', views.post_delete, name="post_delete"),
]

mydjango23/mydjango23/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts', include('accounts.urls')),
    # FIXME : 아래의 url 설정은 blog 기능 구현 후에 pattern_name 으로 변경 예정
    path('', RedirectView.as_view(url='/blog/'), name="root"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

mydjango23/blog/models.py
from django.db import models
from django.urls import reverse


class TimestampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Category(TimestampedModel):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]


class Post(TimestampedModel):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, db_index=True)
    content = models.TextField()
    photo = models.ImageField(upload_to="blog/post/%Y/%m/%d")
    tag_set = models.ManyToManyField('Tag', blank=True)
    status = models.CharField(
        max_length=1,
        # FIXME: 장고 3에서 추가된 TextChoices 기능을 활용
        choices=[
            ('D', '초안'),  # Draft // DB저장값, Label
            ('P', '공개'),  # Published
        ],
        db_index=True,
        default='D',
    )

    def __str__(self):
        return self.title

    # post detail 주소 문자열을 반환
    # detail 페이지를 구현하자마자, 즉시 아래 메서드를 구현합니다.
    def get_absolute_url(self) -> str:
        return reverse("blog:post_detail", args=[self.pk])

    class Meta:
        ordering = ['-id']


class Comment(TimestampedModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    message = models.TextField()

    def __str__(self):
        return self.message

    class Meta:
        ordering = ['-id']


class Tag(TimestampedModel):
    name = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

mydjango23/blog/forms.py
from django import forms
from blog.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = "__all__"

mydjango23/blog/views.py
from django.contrib import messages
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from blog.forms import PostForm
from blog.models import Post


def post_list(request: HttpRequest) -> HttpResponse:
    post_qs = Post.objects.all()
    return render(request, "blog/post_list.html", {
        'post_list': post_qs,
    })


def post_detail(request: HttpRequest, pk: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=pk)
    return render(request, "blog/post_detail.html", {
        'post': post,
    })


def post_new(request: HttpRequest) -> HttpResponse:
    # request.method   # "GET", "POST"

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            saved_post = form.save()
            messages.success(request, "새로운 포스팅을 저장했습니다.")
            return redirect('blog:post_detail', saved_post.pk)
    else:
        form = PostForm()

    return render(request, "blog/post_form.html", {
        "form": form,
    })


def post_edit(request: HttpRequest, pk: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            saved_post = form.save()
            messages.success(request, f"#{pk} 포스팅을 저장했습니다.")
            return redirect('blog:post_detail', saved_post.pk)
    else:
        form = PostForm(instance=post)

    return render(request, "blog/post_form.html", {
        "form": form,
    })


def post_delete(request: HttpRequest, pk: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=pk)

    # GET 요청 : 정말 삭제를 할 것인지, 한 번 더 물어봅니다.
    # POST 요청 : 삭제를 하고, 다른 주소로 이동을 시킵니다.

    # 분기
    if request.method == "POST":
        post.delete()  # 실제로 DB에 DELETE 쿼리 실행(즉시삭제)
        messages.success(request, f"#{pk}")
        return redirect("blog:post_list")

    return render(request, "blog/post_confirm_delete.html", {
        "post": post,
    })

mydjango23/blog/views/cbv.py
# Class Based View(CBV)
#  -> 뷰 함수를 만들어 주는 클래스
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from blog.forms import PostForm
from blog.models import Post

# post_list
post_list = ListView.as_view(
    model=Post,
)

# post_detail
post_detail = DetailView.as_view(
    model=Post,
)


# post_new
class PostCreateView(CreateView):
    model = Post
    form_class = PostForm
    # success_url = reverse_lazy("blog:post_list")

    # def get_success_url(self):
    #     # self.object  # 저장된 모델 인스턴스
    #     post_pk = self.object.pk
    #     return reverse("blog:post_detail", args=[post_pk])  # return 값 : 문자열
    #     # return resolve_url("blog:post_detail", post_pk)  # return 값 : 문자열
    #     # return redirect ("blog:post_detail", post_pk)   # return 값 : HttpResponse
    #     #         {% url "blog:post_detail.html" post_pk %}  # return 값 : 문자열


post_new = PostCreateView.as_view()


# post_edit
class PostUpdatedView(UpdateView):
    model = Post
    form_class = PostForm

    # def get_success_url(self):
    #     post_pk = self.object.pk
    #     return reverse("blog:post_detail", args=[post_pk])


post_edit = PostUpdatedView.as_view(
    model=Post,
    form_class=PostForm,
    # TODO: 가변적으로 URL을 지정할 수 없다.
    # TODO: URL Reverse가 미적용
    # success_url='/blog/',
    # success_url="blog:post_list",  # URL Reverse 미지원
    # success_url=reverse("blog:post_list"),
    success_url=reverse_lazy("blog:post_list"),
)

# post_delete
post_delete = DeleteView.as_view(
    model=Post,
    success_url=reverse_lazy("blog:post_list"),
)

mydjango23/blog/views/fbv.py
from django.contrib import messages
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from blog.forms import PostForm
from blog.models import Post


def post_list(request: HttpRequest) -> HttpResponse:
    post_qs = Post.objects.all()
    return render(request, "blog/post_list.html", {
        'post_list': post_qs,
    })


def post_detail(request: HttpRequest, pk: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=pk)
    return render(request, "blog/post_detail.html", {
        'post': post,
    })


def post_new(request: HttpRequest) -> HttpResponse:
    # request.method   # "GET", "POST"

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            saved_post = form.save()
            messages.success(request, "새로운 포스팅을 저장했습니다.")
            return redirect('blog:post_detail', saved_post.pk)
    else:
        form = PostForm()

    return render(request, "blog/post_form.html", {
        "form": form,
    })


def post_edit(request: HttpRequest, pk: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            saved_post = form.save()
            messages.success(request, f"#{pk} 포스팅을 저장했습니다.")
            return redirect('blog:post_detail', saved_post.pk)
    else:
        form = PostForm(instance=post)

    return render(request, "blog/post_form.html", {
        "form": form,
    })


def post_delete(request: HttpRequest, pk: int) -> HttpResponse:
    post = get_object_or_404(Post, pk=pk)

    # GET 요청 : 정말 삭제를 할 것인지, 한 번 더 물어봅니다.
    # POST 요청 : 삭제를 하고, 다른 주소로 이동을 시킵니다.

    # 분기
    if request.method == "POST":
        post.delete()  # 실제로 DB에 DELETE 쿼리 실행(즉시삭제)
        messages.success(request, f"#{pk}")
        return redirect("blog:post_list")

    return render(request, "blog/post_confirm_delete.html", {
        "post": post,
    })

mydjango23/blog/templates/blog/layout.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>김승아의 블로그</title>
</head>
<body>

<h1>김승아의 블로그</h1>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
{% endif %}

{% block content %}
{% endblock %}

<hr>
&copy; 2021. 김승아 컴퍼니.

</body>
</html>

mydjango23/blog/templates/blog/post_confirm_delete.html
{% extends "blog/layout.html" %}

{% block content %}
    <h2>Post 삭제를 확인</h2>

        <form action="" method="post">
            {% csrf_token %}
            <input type="submit" value="삭제하겠습니다.">
        </form>

        <hr/>

        <a href="{% url "blog:post_detail" post.pk %}">
            Detail로 돌아가기
        </a>
{% endblock %}

mydjango23/blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}

{% block content %}
    <h2>{{ post.title }}</h2>

    <p>
        {% for tag in post.tag_set.all %}
            {{ tag.name }}
        {% endfor %}
    </p>

    <img src="{{ post.photo.url }}" alt="{{ post.title }}">

    {{ post.content|linebreaks }}

    <hr>

    <a href="{% url "blog:post_list" %}">
        포스팅 목록
    </a>

    <a href="{% url "blog:post_edit" post.pk %}">
        포스팅 수정
    </a>

    <a href="{% url "blog:post_delete" post.pk %}">
        포스팅 삭제
    </a>

{% endblock %}

mydjango23/blog/templates/blog/post_form.html
{% block content %}
    <form action="" method="post" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit"/>
    </form>

    <hr/>

    <a href="{% url "blog:post_list" %}">
        목록으로
    </a>

    {% if post %}
        <a href="{% url "blog:post_detail" post.pk %}">
            조회화면으로
        </a>
    {% endif %}
{% endblock %}

mydjango23/blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block content %}
    <h2>Post list</h2>

    <table>
        <thead>
        {% for post in post_list %}
            <tr>
                <td>
                    <a href="{% url "blog:post_detail" post.pk %}">
                        {{ post.title }}
                    </a>
                </td>
            </tr>
        {% endfor %}
        </thead>
    </table>


    <hr>
    <a href="{% url "blog:post_new" %}">
        포스팅 쓰기
    </a>

{% endblock %}